version: "3.8"
services:
  backend_flask_server:
    image: dongho18/connect-gnu-flask:latest
    container_name: backend_flask_server
    ports:
      - "5000:5000"
    volumes:
      - /backend_flask_server:/app
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    user: root
    restart: unless-stopped

volumes:
  jenkins_data:
