version: "3"
services:
  backend_flask_server:
    build: .
    image: dongho18/connect-gnu-flask:latest
    container_name: backend_flask_server
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - .:/code
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - CARD_VARIFICATION_IMAGE_URL=${CARD_VARIFICATION_IMAGE_URL}
    depends_on:
      - nginx
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/lib/docker/cli-plugins/docker-compose:/usr/local/bin/docker-compose
    restart: unless-stopped
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
