version: "3.8"
services:
  app:
    build: .
    image: dongho18/connect-gnu-flask
  production:
    image: dongho18/connect-gnu-flask:${BUILD_NUMBER}
    container_name: backend_flask_server
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: python app.py
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Seoul
    user: root
    privileged: true
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/lib/docker/cli-plugins/docker-compose:/usr/local/bin/docker-compose
    restart: unless-stopped
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
