services:
  backend_flask_server:
    build: .
    container_name: backend_flask_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    platform: linux/amd64
